# Generated by Django 2.2.1 on 2020-07-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='name',
            new_name='names',
        ),
    ]
