# Generated by Django 2.2.1 on 2020-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200630_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edad', models.IntegerField(default=1)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('curp', models.CharField(default='', max_length=16)),
            ],
            options={
                'db_table': 'Example1',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
